### ISSUE TITLE
ModuleNotFoundError: No module named 'cli_satellite'

### ISSUE THREAD

**Issue by goldyfruit** [OpenJarbas/HiveMind-cli#13]
```
(hivemind) pi@rpi4b01:~ $ HiveMind-cli 
Traceback (most recent call last):
  File "/home/pi/.venv/hivemind/bin/HiveMind-cli", line 11, in <module>
    load_entry_point('HiveMind-cli==0.5.0a1', 'console_scripts', 'HiveMind-cli')()
  File "/home/pi/.venv/hivemind/lib/python3.9/site-packages/pkg_resources/__init__.py", line 489, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/home/pi/.venv/hivemind/lib/python3.9/site-packages/pkg_resources/__init__.py", line 2852, in load_entry_point
    return ep.load()
  File "/home/pi/.venv/hivemind/lib/python3.9/site-packages/pkg_resources/__init__.py", line 2443, in load
    return self.resolve()
  File "/home/pi/.venv/hivemind/lib/python3.9/site-packages/pkg_resources/__init__.py", line 2449, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
ModuleNotFoundError: No module named 'cli_satellite'
```

**Comment by JarbasAl** [comment]
fixed
