### ISSUE TITLE
Migrate jarbas_utils to ovos_utils and add zeroconf to deps

### ISSUE THREAD

**Issue by Ashden** [OpenJarbas/HiveMind-cli#4]
Applies when installing HiveMind-cli via pip install

```
    Running setup.py install for HiveMind-cli ... done
Successfully installed Automat-20.2.0 HiveMind-cli-0.4.1 PyYAML-5.4.1 attrs-20.3.0 autobahn-21.3.1 certifi-2020.12.5 cffi-1.14.5 chardet-4.0.0 constantly-15.1.0 cryptography-3.4.7 fasteners-0.16 hyperlink-21.0.0 idna-2.10 ifaddr-0.1.7 incremental-21.3.0 inflection-0.5.1 jarbas-hive-mind-0.10.6 json-database-0.5.5 kthread-0.2.2 lxml-4.6.3 mycroft-messagebus-client-0.9.1 ovos-utils-0.0.8 pexpect-4.8.0 ptyprocess-0.7.0 pyasn1-0.4.8 pyasn1-modules-0.2.8 pycparser-2.20 pycryptodome-3.10.1 pyee-8.1.0 pyopenssl-20.0.1 python-dateutil-2.8.1 pyxdg-0.27 requests-2.25.1 service-identity-18.1.0 six-1.15.0 twisted-21.2.0 txaio-21.2.1 upnpclient-1.0.3 urllib3-1.26.4 websocket-client-0.54.0 zope.interface-5.3.0
(.venv) ashden@DESKTOP-FHEOV53:~/HiveMind-cli$ HiveMind-cli
Traceback (most recent call last):
  File "/home/ashden/HiveMind-cli/.venv/bin/HiveMind-cli", line 11, in <module>
    load_entry_point('HiveMind-cli==0.4.1', 'console_scripts', 'HiveMind-cli')()
  File "/home/ashden/HiveMind-cli/.venv/lib/python3.7/site-packages/pkg_resources/__init__.py", line 489, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/home/ashden/HiveMind-cli/.venv/lib/python3.7/site-packages/pkg_resources/__init__.py", line 2793, in load_entry_point
    return ep.load()
  File "/home/ashden/HiveMind-cli/.venv/lib/python3.7/site-packages/pkg_resources/__init__.py", line 2411, in load
    return self.resolve()
  File "/home/ashden/HiveMind-cli/.venv/lib/python3.7/site-packages/pkg_resources/__init__.py", line 2417, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
  File "/home/ashden/HiveMind-cli/.venv/lib/python3.7/site-packages/cli_satellite/__init__.py", line 1, in <module>
    from jarbas_hive_mind.slave.terminal import HiveMindTerminalProtocol, HiveMindTerminal
  File "/home/ashden/HiveMind-cli/.venv/lib/python3.7/site-packages/jarbas_hive_mind/__init__.py", line 4, in <module>
    from jarbas_hive_mind.master import HiveMind, HiveMindProtocol
  File "/home/ashden/HiveMind-cli/.venv/lib/python3.7/site-packages/jarbas_hive_mind/master/__init__.py", line 12, in <module>
    from jarbas_hive_mind.discovery.ssdp import SSDPServer
  File "/home/ashden/HiveMind-cli/.venv/lib/python3.7/site-packages/jarbas_hive_mind/discovery/__init__.py", line 8, in <module>
    from jarbas_hive_mind.discovery.zero import ZeroScanner
  File "/home/ashden/HiveMind-cli/.venv/lib/python3.7/site-packages/jarbas_hive_mind/discovery/zero.py", line 4, in <module>
    from zeroconf import Zeroconf, ServiceInfo
ModuleNotFoundError: No module named 'zeroconf'
```

After installing zeroconf manually:
```
ModuleNotFoundError: No module named 'jarbas_utils'
```

Python 3.7.3
pip 21.0.1 from /home/ashden/HiveMind-cli/.venv/lib/python3.7/site-packages/pip (python 3.7)

When attempting to use the repository and install the requirements, there's a lock in package version:
```
(.venv) ashden@DESKTOP-FHEOV53:~/HiveMind-cli$ pip install .
Processing /home/ashden/HiveMind-cli
ERROR: Could not find a version that satisfies the requirement jarbas_hive_mind>=0.10.7 (from hivemind-cli)
ERROR: No matching distribution found for jarbas_hive_mind>=0.10.7
```
At the time of this writing, the latest version of jarbas_hive_mind is 0.10.6

**Comment by ChanceNCounter** [comment]
Yep, this has been going on for a long time. We've been distracted. Apologies. It's janitor work, so I'll see if one of us can't get to it today or tomorrow.

**Comment by ChanceNCounter** [comment]
Forgot to explain: `jarbas_utils` has been moved to `ovos_utils` due to its primary dependency belonging to that org, with which we share devs (including Jarbas.)

The packages we use most often were migrated more or less immediately, but some of the others just sat there. Some version mismatches cropped up, owing to "all" users running GitHub installs in venvs on the dev branches.

The main HiveMind people also work on OVOS, which has felt like a higher priority, and MycroftAI's NLP package (Lingua Franca) which is *definitely* a higher priority.

Meantime, the most immediate implementations for HiveMind are intended to be mobile Linux - reference implementations on Manjaro and pmOS - and OVOS. Mobile development has been stalled for a variety of reasons, so... OVOS. And then the mk2 drop happened.

We're sorting ourselves out to try for a long HiveMind sprint. It's overdue. The repos don't just need attention - the next sprint is to implement device-side functionality.

**Comment by ChanceNCounter** [comment]
June 12: problem backburnered for another 2 months by OVOS and parser maintenance. Fail? Remains to be seen.
