### ISSUE TITLE
Can't Connect from mac to Raspberry running Hivemind-cli- Does this look like a valid address?

### ISSUE THREAD

**Issue by Guillaume-slize** [OpenJarbas/HiveMind-cli#8]
I am trying to set-up a small Hivemind network using a raspberry 4B and a mac (macOs Catalina 10.15.7) via Wi-Fi and ssh but I am having trouble connecting to the Hivemind from the mac following the instruction of the wiki.

At the moment I was successful at installing mycroft and HiveMind-core (I think).

On the terminal window of the raspberry (connected to the mac via wi-fi/ ssh) :
`pi@raspberrypi:~ $ python3 HiveMind-core/examples/mycroft_master.py 
2021-07-27 20:06:58.921 - OVOS - jarbas_hive_mind:secure_listen:201 - INFO - HiveMind Listening: wss://0.0.0.0:5678`

I added the key by running the python script on the raspberry:
`python3 HiveMind-core/examples/add_keys.py`

I cloned the HiveMind-cli repository on my mac and installed it via the setup script.
But when I try to use it I have this message:
`MacBook-Pro:HiveMind-cli $ HiveMind-cli --access_key==RESISTENCEisFUTILE --crypto_key==resistanceISfutile --name==JarbasCliTerminal --host==192.168.1.42 
2021-07-27 14:19:04.320 - OVOS - jarbas_hive_mind:unsafe_connect:76 - INFO - Connecting to ws://=192.168.1.42:5678
2021-07-27 14:19:04.321 - OVOS - jarbas_hive_mind:unsafe_connect:77 - WARNING - This listener is unsecured
2021-07-27 14:19:04.335 - OVOS - jarbas_hive_mind.nodes.terminal:clientConnectionFailed:217 - ERROR - Could not find the specified HiveMind entry point
2021-07-27 14:19:04.336 - OVOS - jarbas_hive_mind.nodes.terminal:clientConnectionFailed:219 - DEBUG - Does this look like a valid address? ws://=192.168.1.42:5678
`

Should the host argument be the IP adress of the raspberry? Have I missed a step? 
Thanks a lot for the repository, it looks very promising :) .

**Comment by JarbasAl** [comment]
i think the issue is using the `==` signs, should be a space, does that work?

the host should be the IP address of the raspberry yes

**Comment by Guillaume-slize** [comment]
Thanks for the quick answer and sorry for the silly mistake. However, I still get an error.

Output of the raspberry:
```
pi@raspberrypi:~ $ python3 HiveMind-core/examples/mycroft_master.py 
2021-07-27 20:43:04.980 - OVOS - jarbas_hive_mind:secure_listen:201 - INFO - HiveMind Listening: wss://0.0.0.0:5678
2021-07-27 20:43:09.243 - OVOS - jarbas_hive_mind.nodes.master:unregister_client:282 - INFO - deregistering client: tcp4:192.168.1.7:55620
2021-07-27 20:43:09.248 - OVOS - jarbas_hive_mind.nodes.master:connectionLost:116 - INFO - WebSocket connection lost: [Failure instance: Traceback: <class 'OpenSSL.SSL.Error'>: [('SSL routines', 'ssl3_get_record', 'http request')]
/home/pi/.local/lib/python3.7/site-packages/twisted/internet/posixbase.py:687:_doReadOrWrite
/home/pi/.local/lib/python3.7/site-packages/twisted/internet/tcp.py:246:doRead
/home/pi/.local/lib/python3.7/site-packages/twisted/internet/tcp.py:251:_dataReceived
/home/pi/.local/lib/python3.7/site-packages/twisted/protocols/tls.py:309:dataReceived
--- <exception caught here> ---
/home/pi/.local/lib/python3.7/site-packages/twisted/protocols/tls.py:232:_checkHandshakeStatus
/usr/lib/python3/dist-packages/OpenSSL/SSL.py:1915:do_handshake
/usr/lib/python3/dist-packages/OpenSSL/SSL.py:1647:_raise_ssl_error
/usr/lib/python3/dist-packages/OpenSSL/_util.py:54:exception_from_error_queue
]
Unhandled Error
Traceback (most recent call last):
  File "/home/pi/HiveMind-core/jarbas_hive_mind/__init__.py", line 222, in listen
    return self.secure_listen(factory=factory, protocol=protocol)
  File "/home/pi/HiveMind-core/jarbas_hive_mind/__init__.py", line 203, in secure_listen
    reactor.run()
  File "/home/pi/.local/lib/python3.7/site-packages/twisted/internet/base.py", line 1423, in run
    self.mainLoop()
  File "/home/pi/.local/lib/python3.7/site-packages/twisted/internet/base.py", line 1433, in mainLoop
    reactorBaseSelf.runUntilCurrent()
--- <exception caught here> ---
  File "/home/pi/.local/lib/python3.7/site-packages/twisted/internet/base.py", line 999, in runUntilCurrent
    call.func(*call.args, **call.kw)
  File "/home/pi/.local/lib/python3.7/site-packages/txaio/_common.py", line 136, in _notify_bucket
    notify_one_chunk(calls, self._chunk_size, max(0.0, delay_ms))
  File "/home/pi/.local/lib/python3.7/site-packages/txaio/_common.py", line 130, in notify_one_chunk
    raise RuntimeError(msg)
builtins.RuntimeError: Error(s) processing call_later bucket:
'NoneType' object has no attribute 'shutdown'

```

Output of the mac:

```
MacBook-Pro:HiveMind-flask-template $ HiveMind-cli --access_key=RESISTENCEisFUTILE --crypto_key=resistanceISfutile --name=JarbasCliTerminal --host=192.168.1.42
2021-07-27 14:43:09.179 - OVOS - jarbas_hive_mind:unsafe_connect:76 - INFO - Connecting to ws://192.168.1.42:5678
2021-07-27 14:43:09.180 - OVOS - jarbas_hive_mind:unsafe_connect:77 - WARNING - This listener is unsecured
2021-07-27 14:43:09.221 - OVOS - jarbas_hive_mind.nodes.terminal:onClose:36 - WARNING - HiveMind websocket connection closed: connection was closed uncleanly (peer dropped the TCP connection without previous WebSocket closing handshake)
2021-07-27 14:43:09.223 - OVOS - jarbas_hive_mind.nodes.terminal:onClose:50 - ERROR - ConnectionError
2021-07-27 14:43:09.224 - OVOS - jarbas_hive_mind.nodes.terminal:clientConnectionLost:232 - ERROR - HiveMind connection lost: [Failure instance: Traceback (failure with no frames): <class 'twisted.internet.error.ConnectionDone'>: Connection was closed cleanly.
] .. retrying ..
2021-07-27 14:43:09.225 - OVOS - jarbas_hive_mind.nodes.terminal:clientConnectionLost:239 - ERROR - HiveMind connection lost: [Failure instance: Traceback (failure with no frames): <class 'twisted.internet.error.ConnectionDone'>: Connection was closed cleanly.
]
```

**Comment by JarbasAl** [comment]
the pi is listening for https connections, but you are trying to connect by http, this piece of the code and docs need some polishing...

to use ssl you need to specify the protocol in the host argument, `--host=wss://192.168.1.42`

```
MacBook-Pro:HiveMind-flask-template $ HiveMind-cli --access_key=RESISTENCEisFUTILE --crypto_key=resistanceISfutile --name=JarbasCliTerminal --host=wss://192.168.1.42
2
```

**Comment by Guillaume-slize** [comment]
The connection works :) . Thanks a lot.

**Comment by ChanceNCounter** [comment]
Let us know about any mic issues. I've been having trouble with Mac clients, but I haven't tried that hard yet ;)
